apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-toolbox
  namespace: ai-toolbox
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.proxy: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"ai-toolbox"}}'
  labels:
    app: ai-toolbox
